name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y sassc
    - name: Test sass to css compilation
      run: |
        pwd
        ls
