name: CI

on: [push]

jobs:
  build:

    runs-on: fedora-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo dnf install -y sassc
    - name: Run a multi-line script
      run: echo testing
